### PR TITLE
6 bug code quality test doesnt works

### PR DESCRIPTION
**Pull request by WhereAreBugs**

### CODE REVIEW

**Comment by NaturalSelect** [comment]
https://github.com/Async-Lab/CPP_project_1/blob/2485fc55f75dfa4178890daa81430810d0c1725d/.github/customs/python/addInfoTest.py#L130

**Review by YYDanielJr — APPROVED** [review]

**Comment by NaturalSelect** [comment]
`test_obj.communicate` will wait sub process exit

**Comment by NaturalSelect** [comment]
See also: [Python Subprocess Doc](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.communicate)

**Comment by NaturalSelect** [comment]
加个原始输出output吧，方便定位bug

**Pull request merged**
